### ISSUE TITLE
missing many sensor values

### ISSUE THREAD

**Issue by Qlink84** [kallex/PromDapter#1]
great extension for hwinfo64!
unfortunately i'm missing many sensor values when i open localhost:10445/metrics which are shown in hwinfo64 sensors window

e.g. motherboard infos/temperatures are missing
![image](https://user-images.githubusercontent.com/15886027/86618704-ae290400-bfb9-11ea-82f1-5588da23d67f.png)
![image](https://user-images.githubusercontent.com/15886027/86618880-ecbebe80-bfb9-11ea-8f6c-0f77d23e0068.png)
cpu temperature missing

can you tell me how i can add them to the metrics website ?
i don't understand the change the mapping.yaml correctly

i've tried to add following lines:

# Motherboard
    - '(?<Entity>Motherboard) (?<MetricName>Temperature)'

but not luck with that...

best regards

**Comment by kallex** [comment]
Sorry for slow response, didn't get alert. I'll look into this asap.

**Comment by kallex** [comment]
Your idea is right about the entity part, however there is no "Temperature" in the name of those sensors.

You could try like this to have just "entity" with metric "c" that will be the unit

- '(?<Entity>Motherboard|CPU \(PECI\)|CPU|Auxiliary|SYSTIN1|SYSTIN2|SYSTIN3)'

... or with fixed entity-name as "Temperature" and then the metric named more specfically

- '(?<Entity_Temperature>)(?<MetricName>Motherboard|CPU \(PECI\)|CPU|Auxiliary|SYSTIN1|SYSTIN2|SYSTIN3)'

I would likely myself go with the latter one, with Entity_Temperature fixed, so that the Metric has some sensible name still.

This altogether is something I want to address better, but I have not yet came up with solution.

**Comment by kallex** [comment]
Closed for now (expeted to be resolved by above suggestions). Reopen if they don't resolve.
